name: shell commands

on: [push]

jobs: 
    run-shell-commands:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "hello world"
        - name: multiple script
          run: |
            node -v
            npm -v
        - name: python shell
          run: |
            import platform
            print(platform.processor())
          shell: python
    run-windows-powershell:
      runs-on: windows-latest
      steps:
        - name: directory run-windows-powershell
          run: Get-Location
        - name: bash
          run: pwd
          shell: bash